require "laurent.launch"
require "laurent.options"
require "laurent.keymaps"
require "laurent.autocmds"

-- Plugin list
SpecList "laurent.colorschemes"
SpecList "laurent.dadbod"
Spec "laurent.lualine"
Spec "laurent.telescope"
Spec "laurent.comments"
Spec "laurent.gitsigns"
Spec "laurent.lazygit"
Spec "laurent.toggleterm"
Spec "laurent.treesitter"
Spec "laurent.lspconfig"
Spec "laurent.mason"
Spec "laurent.mason-config"
Spec "laurent.lspconfig"
Spec "laurent.cmp-nvim-lsp"
Spec "laurent.cmp-buffer"
Spec "laurent.cmp-path"
Spec "laurent.cmp-cmdline"
Spec "laurent.nvim-cmp"
Spec "laurent.harpoon"
Spec "laurent.presence"
Spec "laurent.indentation"
Spec "laurent.autopairs"
Spec "laurent.move"
Spec "laurent.todocomments"
Spec "laurent.luasnip"
Spec "laurent.boo"
Spec "laurent.trouble"
Spec "laurent.oil"
Spec "laurent.undotree"
Spec "laurent.neodev"
Spec "laurent.flash"
Spec "laurent.colorizer"
Spec "laurent.doge"
Spec "laurent.tailwind"

-- Local plugins
Spec "laurent.epi_headers"
Spec "laurent.headersnvim"
Spec "laurent.nshare"

require "laurent.lazy"
